// <auto-generated />
namespace ITI.ItSchool.ExerciseDictationContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialPlusUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialPlusUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201506222016023_InitialPlusUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
