// <auto-generated />
namespace ITI.ItSchool.ExerciseContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingExercisesResults : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingExercisesResults));
        
        string IMigrationMetadata.Id
        {
            get { return "201507011300129_AddingExercisesResults"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
